name: Auto Post Two Sites Gemini Media

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install google-generativeai requests beautifulsoup4 facebook-sdk
      - name: List files
        run: ls -R
      - name: Run auto poster with media
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          FACEBOOK_ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
        run: python auto_fb_post_two_sites_media.py
