name: Auto Post Multi Gemini

on:
  schedule:
    - cron: '0 */6 * * *'  # Chạy mỗi 6 giờ
  workflow_dispatch:         # Cho phép chạy thủ công

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install google-generativeai requests beautifulsoup4 facebook-sdk

      - name: Debug - List files
        run: ls -R

      - name: Run auto poster
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          FACEBOOK_ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
        run: python auto_fb_post_multi_gemini.py
